# Generated by Django 5.2 on 2025-05-05 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefacto',
            name='tipo',
            field=models.CharField(choices=[('AREQ', 'Análisis Requisitos'), ('DISE', 'Diseño'), ('DEVS', 'Desarrollo'), ('PRUE', 'Pruebas'), ('DESP', 'Despliegue')], max_length=10),
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='documentacion.project')),
            ],
        ),
        migrations.CreateModel(
            name='SubArtefacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('enlace', models.URLField(blank=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subartefactos', to='documentacion.fase')),
            ],
        ),
    ]
