# Generated by Django 5.2 on 2025-05-13 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentacion", "0002_alter_artefacto_tipo_fase_subartefacto"),
    ]

    operations = [
        migrations.AddField(
            model_name="artefacto",
            name="fase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artefactos",
                to="documentacion.fase",
            ),
        ),
        migrations.AddField(
            model_name="artefacto",
            name="subartefacto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artefactos",
                to="documentacion.subartefacto",
            ),
        ),
    ]
